-- ============================================================================
-- FORXA · 02 · Tablas de las landings (Álabes, Arcus, Portón) y portafolio
-- Mismo modelo de datos que ya usaban los sitios (Nivel 1: sin cambios de
-- estructura), ahora todo en un solo proyecto de Supabase.
-- Las políticas de acceso están en 06_politicas.sql.
-- ============================================================================

-- Álabes -------------------------------------------------------------------
create table if not exists public.units (
  code text primary key,
  kind text not null default 'suite',          -- 'suite' | 'local'
  grupo text,
  title text not null,
  tag text,
  area text,
  status text not null default 'disponible'
    check (status in ('disponible','reservado','vendido')),
  dorm text,
  banos text,
  extra text,
  ficha text,
  thumb text,
  sort_order integer not null default 0,
  updated_at timestamptz not null default now()
);

-- Arcus --------------------------------------------------------------------
create table if not exists public.arcus_units (
  code text primary key,
  kind text not null default 'suite' check (kind in ('suite','loft','local','isla')),
  grupo text,
  title text not null,
  tag text,
  area text,
  status text not null default 'disponible'
    check (status in ('disponible','reservado','vendido')),
  dorm text,
  banos text,
  extra text,
  ficha text,
  thumb text,
  sort_order integer not null default 0,
  updated_at timestamptz not null default now()
);

-- Portón del Valle -----------------------------------------------------------
create table if not exists public.lots (
  code text primary key,
  status text not null default 'disponible'
    check (status in ('disponible','reservado','no_disponible')),
  area numeric,
  price numeric,
  cx numeric not null default 50,
  cy numeric not null default 50,
  points jsonb,                                 -- polígono [[x,y],...] trazado sobre el plano
  updated_at timestamptz not null default now()
);

create table if not exists public.slider_images (
  id bigint generated by default as identity primary key,
  src text not null,
  alt text default '',
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

-- Portafolio (landing principal FORXA) ---------------------------------------
create table if not exists public.projects (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  url text not null,
  tagline text,
  cover_url text,
  ubicacion text,
  tipo text,                                    -- ej. 'Suites y locales', 'Lotes'
  visible boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);
-- Columnas nuevas si la tabla ya existía:
alter table public.projects add column if not exists ubicacion text;
alter table public.projects add column if not exists tipo text;
alter table public.projects add column if not exists visible boolean not null default true;

-- updated_at automático ------------------------------------------------------
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end;
$$;

drop trigger if exists units_updated_at on public.units;
create trigger units_updated_at before update on public.units
  for each row execute function public.set_updated_at();
drop trigger if exists arcus_units_updated_at on public.arcus_units;
create trigger arcus_units_updated_at before update on public.arcus_units
  for each row execute function public.set_updated_at();
drop trigger if exists lots_updated_at on public.lots;
create trigger lots_updated_at before update on public.lots
  for each row execute function public.set_updated_at();

alter table public.units         enable row level security;
alter table public.arcus_units   enable row level security;
alter table public.lots          enable row level security;
alter table public.slider_images enable row level security;
alter table public.projects      enable row level security;

-- Storage público para imágenes de los sitios.
-- Carpetas: alabes/  arcus/  porton/  portafolio/  (una por proyecto)
insert into storage.buckets (id, name, public)
values ('site-images', 'site-images', true)
on conflict (id) do nothing;

-- Portafolio inicial (solo si la tabla está vacía). La migración de datos
-- (scripts/migrar_datos.mjs) reemplaza esto con lo que ya tenías cargado.
insert into public.projects (name, url, tagline, cover_url, ubicacion, tipo, sort_order)
select * from (values
  ('Álabes', '/alabes/', 'Suites, departamentos y locales comerciales en la calle del Batán.', 'assets/covers/alabes.jpg', 'Cuenca', 'Suites y locales', 1),
  ('Arcus Suites & Lofts', '/arcus/', 'Suites, lofts y espacios comerciales sobre la Remigio Tamariz Crespo.', 'assets/covers/arcus.jpg', 'Cuenca', 'Suites, lofts y locales', 2),
  ('Portón del Valle', '/porton/', 'Lotes y desarrollo residencial en el valle de Yunguilla.', 'assets/covers/porton-del-valle.jpg', 'Yunguilla', 'Lotes', 3),
  ('AURA', 'https://www.kapitalf.com/', 'Edificio residencial Ordóñez Lasso.', 'assets/covers/aura.jpg', 'Cuenca', 'Departamentos', 4)
) as seed(name, url, tagline, cover_url, ubicacion, tipo, sort_order)
where not exists (select 1 from public.projects);
